name: midjourney_client
description: > 
  Unofficial midjourney client that gives you possibility to generates images! 
  Now, it utilizes the Discord API to communicate with the bot.
version: 0.2.0-dev.2
repository: https://github.com/hawkkiller/midjourney-client

environment:
  sdk: ^3.0.5

dependencies:
  snowflaker: ^1.0.3
  http: ^1.0.0
  l: ^4.0.1
  meta: ^1.9.1
  ws: ^0.0.3-dev.placeholder
  collection: ^1.17.2

dev_dependencies:
  sizzle_lints: ^1.0.10
  test: ^1.21.0
