name: Code Quality

on:
  push:
      branches: [main]    

  pull_request:
      branches: [main]

jobs:
  analyze:
      name: Code Quality
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v3

          - uses: dart-lang/setup-dart@v1
            with:
              sdk: "3.0.5"

          - name: Get Packages
            run: dart pub get

          - name: Analyze
            run: dart analyze --fatal-infos --fatal-warnings .

          - name: Format
            run: dart format --set-exit-if-changed .
            
          - name: Validate
            run: dart pub publish --dry-run