name: Release the library

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CHANGELOG.md
            pubspec.yaml
            lib/*
            example/*
            test/*
          body: ${{steps.build_changelog.outputs.changelog}}
          token: ${{ secrets.GITHUB_TOKEN }}
          # decide whether to publish as prerelease or not
          # check the ref to see if it's a prerelease or not
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'dev') }}


  pub-publish:
    permissions:
      id-token: 'write'
    
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1