name: Release the library

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CHANGELOG.md
            pubspec.yaml
            lib/*
            example/*
            test/*
          tag_name: ${{ github.ref }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false


  pub-publish:
    permissions:
      id-token: 'write'
    
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1