name: Release the library

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # - name: Build Changelog
      #   id: build_changelog
      #   uses: mikepenz/release-changelog-builder-action@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'dev') }}
          files: |
            CHANGELOG.md
            LICENSE
            pubspec.yaml
            lib/*
            example/*
            test/*
      
  pub-publish:
    permissions:
      id-token: 'write'
    
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1